wandb_version: 1

attention_size:
  value: 956
batch_size:
  value: 16
dropout:
  value: 0.2
fc1_size:
  value: 781
fc2_size:
  value: 940
fc3_size:
  value: 100
input_size:
  value: 1
learning_rate:
  value: 0.0001
lrf:
  value: 0.1
num_layers:
  value: 2
output_size:
  value: 6
pf_dim:
  value: 974
pre_size:
  value: 944
training_epoch:
  value: 5000
