wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    start_time: 1699586227
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.7.4
      5: 0.12.7
      8:
      - 3
      - 5
attention_size:
  desc: null
  value: 754
batch_size:
  desc: null
  value: 16
dropout:
  desc: null
  value: 0.4
fc1_size:
  desc: null
  value: 113
fc2_size:
  desc: null
  value: 308
fc3_size:
  desc: null
  value: 497
input_size:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 1.0e-05
lrf:
  desc: null
  value: 0.1
num_layers:
  desc: null
  value: 5
output_size:
  desc: null
  value: 6
pf_dim:
  desc: null
  value: 1015
pre_size:
  desc: null
  value: 659
training_epoch:
  desc: null
  value: 5000
