wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    start_time: 1699586207
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.7.4
      5: 0.12.7
      8:
      - 3
      - 5
attention_size:
  desc: null
  value: 956
batch_size:
  desc: null
  value: 16
dropout:
  desc: null
  value: 0.2
fc1_size:
  desc: null
  value: 781
fc2_size:
  desc: null
  value: 940
fc3_size:
  desc: null
  value: 100
input_size:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0001
lrf:
  desc: null
  value: 0.1
num_layers:
  desc: null
  value: 2
output_size:
  desc: null
  value: 6
pf_dim:
  desc: null
  value: 974
pre_size:
  desc: null
  value: 944
training_epoch:
  desc: null
  value: 5000
